apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nginx
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
# catalog-info.yaml (backstage)
  annotations:
    backstage.io/kubernetes-label-selector: 'nginx'
spec:
  type: service
  owner: guest
  lifecycle: experimental
